// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20211210122834_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Models.Genre", b =>
                {
                    b.Property<int>("GenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreID");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreID = 1,
                            Description = "An action story is similar to adventure, and the protagonist usually takes a risky turn, which leads to desperate situations (including explosions, fight scenes, daring escapes, etc.).",
                            Name = "Action"
                        },
                        new
                        {
                            GenreID = 2,
                            Description = "An adventure story is about a protagonist who journeys to epic or distant places to accomplish something. It can have many other genre elements included within it, because it is a very open genre.",
                            Name = "Adventure"
                        },
                        new
                        {
                            GenreID = 3,
                            Description = "Technically speaking, animation is more of a medium than a film genre in and of itself; as a result, animated movies can run the gamut of traditional genres with the only common factor being that they don’t rely predominantly on live action footage.",
                            Name = "Animation"
                        },
                        new
                        {
                            GenreID = 4,
                            Description = "Comedy is a story that tells about a series of funny or comical events, intended to make the audience laugh. It is a very open genre, and thus crosses over with many other genres on a frequent basis.",
                            Name = "Comedy"
                        },
                        new
                        {
                            GenreID = 5,
                            Description = "A subgenre which combines the romance genre with comedy, focusing on two or more individuals as they discover and attempt to deal with their romantic love, attractions to each other. The stereotypical plot line follows the boy-gets-girl, boy-loses-girl, boy gets girl back again sequence. ",
                            Name = "Romantic Comedy"
                        },
                        new
                        {
                            GenreID = 6,
                            Description = "A subgenre which combines the romance genre with comedy, focusing on two or more individuals as they discover and attempt to deal with their romantic love, attractions to each other. ",
                            Name = "Crime"
                        },
                        new
                        {
                            GenreID = 7,
                            Description = "Within film, television and radio (but not theatre), drama is a genre of narrative fiction (or semi-fiction) intended to be more serious than humorous in tone,",
                            Name = "Drama"
                        },
                        new
                        {
                            GenreID = 8,
                            Description = "Science fiction is similar to fantasy, except stories in this genre use scientific understanding to explain the universe that it takes place in. It generally includes or is centered on the presumed effects or ramifications of computers or machines; travel through space, time or alternate universes; alien life-forms; genetic engineering; or other such things. ",
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            GenreID = 9,
                            Description = "Romance novels are emotion-driven stories that are primarily focused on the relationship between the main characters of the story.",
                            Name = "Romance"
                        },
                        new
                        {
                            GenreID = 10,
                            Description = "A fantasy story is about magic or supernatural forces, rather than technology, though it often is made to include elements of other genres, such as science fiction elements, for instance computers or DNA, if it happens to take place in a modern or future era. ",
                            Name = "Fantasy"
                        },
                        new
                        {
                            GenreID = 11,
                            Description = "The coverage of sports as a television program, on radio and other broadcasting media. It usually involves one or more sports commentators describing the events as they happen, which is called colour commentary.",
                            Name = "Sport"
                        },
                        new
                        {
                            GenreID = 12,
                            Description = "tories in the Western genre are set in the American West, between the time of the Civil war and the early nineteenth century.",
                            Name = "Western"
                        },
                        new
                        {
                            GenreID = 13,
                            Description = "A Thriller is a story that is usually a mix of fear and excitement. It has traits from the suspense genre and often from the action, adventure or mystery genres, but the level of terror makes it borderline horror fiction at times as well. ",
                            Name = "Thriller"
                        },
                        new
                        {
                            GenreID = 14,
                            Description = "The family saga is a genre of literature which chronicles the lives and doings of a family or a number of related or interconnected families over a period of time. ",
                            Name = "Family"
                        });
                });

            modelBuilder.Entity("Domain.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Operation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Domain.Models.Movie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Director")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.Property<decimal>("Gross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("ImageFile")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageMimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("ID");

                    b.HasIndex("GenreID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Director = "Rob Reiner",
                            GenreID = 5,
                            Gross = 92823600m,
                            Rating = 7.5999999999999996,
                            ReleaseDate = new DateTime(1989, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "When Harry Met Sally"
                        },
                        new
                        {
                            ID = 2,
                            Director = "Ivan Reitman",
                            GenreID = 4,
                            Gross = 13612564m,
                            Rating = 6.5,
                            ReleaseDate = new DateTime(1984, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ghostbusters"
                        },
                        new
                        {
                            ID = 3,
                            Director = "Ivan Reitman",
                            GenreID = 4,
                            Gross = 112494738m,
                            Rating = 6.5,
                            ReleaseDate = new DateTime(1986, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ghostbusters 2"
                        },
                        new
                        {
                            ID = 4,
                            Director = "Howard Hawks",
                            GenreID = 12,
                            Gross = 5750000m,
                            Rating = 8.0999999999999996,
                            ReleaseDate = new DateTime(1959, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rio Bravo"
                        },
                        new
                        {
                            ID = 5,
                            Director = "Frank Darabont",
                            GenreID = 7,
                            Gross = 28341469m,
                            Rating = 9.3000000000000007,
                            ReleaseDate = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            ID = 6,
                            Director = "Francis Ford Coppola",
                            GenreID = 7,
                            Gross = 134821952m,
                            Rating = 9.1999999999999993,
                            ReleaseDate = new DateTime(1972, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Godfather"
                        },
                        new
                        {
                            ID = 7,
                            Director = "Quentin Tarantino",
                            GenreID = 13,
                            Gross = 107930000m,
                            Rating = 8.9000000000000004,
                            ReleaseDate = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            ID = 8,
                            Director = "Steven Spielberg",
                            GenreID = 7,
                            Gross = 96067179m,
                            Rating = 8.9000000000000004,
                            ReleaseDate = new DateTime(1994, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Schindlers List"
                        },
                        new
                        {
                            ID = 9,
                            Director = "Christopher Nolan",
                            GenreID = 1,
                            Gross = 533316061m,
                            Rating = 9.0,
                            ReleaseDate = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            ID = 10,
                            Director = "Peter Jackson",
                            GenreID = 1,
                            Gross = 377019252m,
                            Rating = 8.9000000000000004,
                            ReleaseDate = new DateTime(2003, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            ID = 11,
                            Director = "George Lucas",
                            GenreID = 1,
                            Gross = 460935665m,
                            Rating = 8.6999999999999993,
                            ReleaseDate = new DateTime(1977, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars"
                        },
                        new
                        {
                            ID = 12,
                            Director = "The Wachowski Brothers",
                            GenreID = 8,
                            Gross = 171383253m,
                            Rating = 8.6999999999999993,
                            ReleaseDate = new DateTime(1999, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Matrix"
                        },
                        new
                        {
                            ID = 13,
                            Director = "Robert Zemeckis",
                            GenreID = 4,
                            Gross = 329691196m,
                            Rating = 8.8000000000000007,
                            ReleaseDate = new DateTime(1994, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            ID = 14,
                            Director = " Terry Gilliam & Terry Jones",
                            GenreID = 4,
                            Gross = 1229197m,
                            Rating = 8.3000000000000007,
                            ReleaseDate = new DateTime(1975, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Monty Python and the Holy Grail"
                        },
                        new
                        {
                            ID = 15,
                            Director = "Stanley Kubrick",
                            GenreID = 8,
                            Gross = 56715371m,
                            Rating = 8.3000000000000007,
                            ReleaseDate = new DateTime(1968, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "2001: A Space Odyssey"
                        },
                        new
                        {
                            ID = 16,
                            Director = "Robert Zemeckis",
                            GenreID = 14,
                            Gross = 210609762m,
                            Rating = 8.5,
                            ReleaseDate = new DateTime(1989, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Back to the Future"
                        },
                        new
                        {
                            ID = 17,
                            Director = "Pete Docter & David Silverman",
                            GenreID = 14,
                            Gross = 289907418m,
                            Rating = 8.0999999999999996,
                            ReleaseDate = new DateTime(2001, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Monsters Inc"
                        });
                });

            modelBuilder.Entity("Domain.Models.Movie", b =>
                {
                    b.HasOne("Domain.Models.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Domain.Models.Genre", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
